const driver = {
  CONFIG_BANK: 0x0B,
  BANK_ADDRESS: 0xFD,
  function: {
    MODE_REGISTER: 0x00,
    FRAME_REGISTER: 0x01,
    AUTOPLAY1_REGISTER: 0x02,
    AUTOPLAY2_REGISTER: 0x03,
    BLINK_REGISTER: 0x05,
    AUDIOSYNC_REGISTER: 0x06,
    BREATH1_REGISTER: 0x08,
    BREATH2_REGISTER: 0x09,
    SHUTDOWN_REGISTER: 0x0A,
    GAIN_REGISTER: 0x0B,
    ADC_REGISTER: 0x0C
  }
};